Repository WildCodeSchool/lyon-js-sept2020-p3-vh-api, pull requests merged in 2021-01, with the labels that each got.

#22 Création de la route events
  controllers/events.js
  migrations/20210103183344-addTestsEvents.js
  migrations/sqls/20210103183344-addTestsEvents-down.sql
  migrations/sqls/20210103183344-addTestsEvents-up.sql
  models/events.js
  package-lock.json
  package.json
  routes/events.js
  routes/index.js
  tests/events-endpoints.test.js
  tests/user-endpoints.test.js
Labels: Ready for validation

#21 Refacto route contact
  .env.sample
  app.js
  controllers/contact.js
  env.js
  migrations/20201228181231-addPurposeOnMessages.js
  migrations/sqls/20201228181231-addPurposeOnMessages-down.sql
  migrations/sqls/20201228181231-addPurposeOnMessages-up.sql
  models/contact.js
  package-lock.json
  package.json
Labels: Ready for validation

#25 Address models and controllers created
  controllers/adress.js
  controllers/sponsors.js
  models/adress.js
  models/sponsors.js
  routes/adress.js
  routes/index.js
Labels: Ready for validation

#19 Route animateurs
  controllers/users.js
  models/users.js
  routes/index.js
  routes/users.js
Labels: Ready for validation

#26 Ajout d'une route pour trouver un événement par son id
  controllers/events.js
  models/events.js
  routes/events.js
Labels: Ready for validation

#28 migrationsupdate table user
  migrations/20210106105646-updateTableAnimator.js
  migrations/sqls/20210106105646-updateTableAnimator-down.sql
  migrations/sqls/20210106105646-updateTableAnimator-up.sql
Labels: Fixed - Ready for prod

#29 Modification de la route events
  app.js
  controllers/events.js
  migrations/20210106113005-fieldAvailabilitiesEvents.js
  migrations/sqls/20210106113005-fieldAvailabilitiesEvents-down.sql
  migrations/sqls/20210106113005-fieldAvailabilitiesEvents-up.sql
  models/events.js
  tests/events-endpoints.test.js
Labels: Ready for validation

#35 middleware requireAdmin added
  middlewares/requireAdmin.js
  routes/auth.js
Labels: Ready for validation

#37 methode GetbyId pour la route sponsors
  controllers/sponsors.js
  models/sponsors.js
  routes/sponsors.js
Labels: Ready for validation

#34 Reviews route
  controllers/events.js
  controllers/reviews.js
  models/reviews.js
  package-lock.json
  package.json
  routes/index.js
  routes/reviews.js
Labels: Ready for prod

#31 Création de la route FAQ
  .github/workflows/e2e-api-tests.yml
  app.js
  controllers/faq.js
  controllers/wine.js
  migrations/20210107141140-createFAQTable.js
  migrations/sqls/20210107141140-createFAQTable-down.sql
  migrations/sqls/20210107141140-createFAQTable-up.sql
  models/faq.js
  routes/faq.js
  routes/index.js
Labels: Ready for validation

#39 Add name on table carrousel
  migrations/20210119085923-addNameFieldOnCarousel.js
  migrations/sqls/20210119085923-addNameFieldOnCarousel-down.sql
  migrations/sqls/20210119085923-addNameFieldOnCarousel-up.sql
  models/wine.js
Labels: Ready for validation

#40 Route carrousel get one
  controllers/carrousel.js
  controllers/sponsors.js
  models/carrousel.js
  models/sponsors.js
  routes/carrousel.js
Labels: Ready for validation

#38 Order route
  controllers/order.js
  migrations/20210112154421-order-id.js
  migrations/sqls/20210112154421-order-id-down.sql
  migrations/sqls/20210112154421-order-id-up.sql
  models/events.js
  models/order.js
  package-lock.json
  package.json
  routes/index.js
  routes/order.js
  tests/events-endpoints.test.js
Labels: Ready for validation

#41 migration pour que le champ id soit compatible avec react-admin
  migrations/20210119111345-updateTableFaq.js
  migrations/20210119112039-updatetableFaq.js
  migrations/sqls/20201202110024-initDB-down.sql
  migrations/sqls/20210119111345-updateTableFaq-down.sql
  migrations/sqls/20210119111345-updateTableFaq-up.sql
  migrations/sqls/20210119112039-updatetableFaq-down.sql
  migrations/sqls/20210119112039-updatetableFaq-up.sql
  models/faq.js
Labels: Ready for validation

#42 Connect with calendar
  controllers/events.js
  models/events.js
Labels: Ready for validation

#33 Upload fichiers
  app.js
  controllers/sponsors.js
  middlewares/handleImageUpload.js
  middlewares/requireRequestBody.js
  models/sponsors.js
  package-lock.json
  package.json
  routes/sponsors.js
Labels: Ready for validation

#43 Envoi de mail à la confirmation de commande et 48h avant l'événement
  migrations/20210121132858-addReminderMailFieldOnOrderTable.js
  migrations/sqls/20210121132858-addReminderMailFieldOnOrderTable-down.sql
  migrations/sqls/20210121132858-addReminderMailFieldOnOrderTable-up.sql
  models/order.js
  package.json
Labels: Ready for validation

#46 Moderator route
  controllers/events.js
  controllers/users.js
  middlewares/handleImageUpload.js
  models/events.js
  models/users.js
  routes/events.js
Labels: Ready for validation

#45 Modification de la route order pour coller aux exigences de react-admin
  models/order.js
Labels: Ready for validation

#47 Adaptation de l'API à React Admin
  controllers/carrousel.js
  controllers/events.js
  controllers/sponsors.js
  controllers/users.js
  controllers/wine.js
  models/carrousel.js
  models/events.js
  models/reviews.js
  models/sponsors.js
  models/users.js
  models/wine.js
  routes/carrousel.js
  routes/sponsors.js
  routes/users.js
  routes/wine.js
Labels: Ready for validation

#49 User account
  controllers/reviews.js
  migrations/20210127165531-review-id.js
  migrations/sqls/20210127165531-review-id-down.sql
  migrations/sqls/20210127165531-review-id-up.sql
  models/contact.js
  models/order.js
  models/reviews.js
  models/users.js
  routes/currentUser.js
  routes/index.js
  routes/reviews.js
Labels: Ready for validation

#51 Nettoyage des migrations
  migrations/20201226213448-addWines.js
  migrations/20201226215838-addSlidesOnCarrousel.js
  migrations/20210106105646-updateTableAnimator.js
  migrations/sqls/20201226213448-addWines-down.sql
  migrations/sqls/20201226213448-addWines-up.sql
  migrations/sqls/20201226215838-addSlidesOnCarrousel-down.sql
  migrations/sqls/20201226215838-addSlidesOnCarrousel-up.sql
  migrations/sqls/20201226222429-addTestUsers-up.sql
  migrations/sqls/20210103183344-addTestsEvents-up.sql
  migrations/sqls/20210106105646-updateTableAnimator-down.sql
  migrations/sqls/20210106105646-updateTableAnimator-up.sql
  migrations/sqls/20210106113005-fieldAvailabilitiesEvents-up.sql
Labels: Ready for validation

#50 added a route to link the front when a visitor want to receive the ne…
  .env.sample
  controllers/contact.js
  env.js
  models/contact.js
  routes/contact.js
Labels: Ready for validation
